version: '3.3'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ashu
      MYSQL_DATABASE: Reap
      MYSQL_USER: ashu
      MYSQL_PASSWORD: ashu
    restart: always
    ports:
      - 3307:3306
    networks:
      - backendNetwork
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql

  spring-boot:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: spring-boot
    ports:
      - 5050:5050
    networks:
      - backendNetwork

volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork: